### ISSUE TITLE
Everything vanishes (Paired with Overhaul)

### ISSUE THREAD

**Issue by NoScope-CraZed** [chatrat12/Terraria3D#27]
While running this mod with Overhaul, after killing some enemies, or over time
, the terrain vanishes and is completely invisible. It is interactable, but enemies are invisible, water is invisible, etc.
![20190203181514_1](https://user-images.githubusercontent.com/47306229/52183625-fac64980-27df-11e9-9f66-83f0cbfcc8e6.jpg)
![20190203181406_1](https://user-images.githubusercontent.com/47306229/52183626-fac64980-27df-11e9-9137-71df91aeabce.jpg)

**Comment by prgmatic** [comment]
![image](https://user-images.githubusercontent.com/251682/52241693-6670eb00-28a2-11e9-9d85-5e24c9d7320c.png)
Tested it out, background stopped rendering after a while. Have not gotten world to disappear yet. I'll keep playing with it.
